Fix missing comma in boilerplate/aom/defaults-PD
Using the `PD` status in the metadata block of a Bikeshed .bs file currently fails with:
FATAL ERROR: Error loading defaults JSON:
Expecting ',' delimiter: line 7 column 2 (char 171)
Did not generate, due to fatal errors